Skip ill-formatted products SKUs
A product doesn't follow the usual product code format and causes
product scraping to fail. Log such cases and skip them so we can revisit
these outliers later.

The unusual product code produces the following error:
  builtins.ValueError: Wrong format for product code: 4237008Q

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@gmail.com>