Fix: IndexError when SKU returns empty price info
When a batch price query fails with a 400 error, the code falls back to
querying each SKU individually. However, some SKUs return an empty list
instead of throwing an exception, causing an IndexError when accessing [0].

  DEBUG:canadiantracker.triangle:Sending batched price info query request: ntry=0 batch_size=1 sku_codes=['0182910']
  DEBUG:canadiantracker.triangle:Received 0 price infos
  builtins.IndexError: list index out of range

Check that the result is non-empty before accessing the first element.

Signed-off-by: Jérémie Galarneau <jeremie.galarneau@gmail.com>