Fix type warnings in http.py
Add None checks to fix these warnings:

    /home/simark/src/CanadianTracker/src/canadiantracker/http.py
      /home/simark/src/CanadianTracker/src/canadiantracker/http.py:74:60 - error: "skus" is not a known member of "None" (reportOptionalMemberAccess)
      /home/simark/src/CanadianTracker/src/canadiantracker/http.py:80:69 - error: "samples" is not a known member of "None" (reportOptionalMemberAccess)

In practice it fixes this internal server error when getting a product
that doesn't exist:

    $ curl -i http://localhost:5001/api/products/1234567P
    HTTP/1.1 500 Internal Server Error
    date: Thu, 09 Mar 2023 04:33:14 GMT
    server: uvicorn
    content-length: 21
    content-type: text/plain; charset=utf-8

    Internal Server Error%

Server-side:

    ...
      File "/home/simark/src/CanadianTracker/src/canadiantracker/http.py", line 74, in api_product
        return {"skus": [serialize_sku(sku) for sku in product.skus]}
    AttributeError: 'NoneType' object has no attribute 'skus'

After the patch:

    $ curl -i http://localhost:5001/api/products/1234567P
    HTTP/1.1 404 Not Found
    date: Thu, 09 Mar 2023 04:34:25 GMT
    server: uvicorn
    content-length: 30
    content-type: application/json

    {"detail":"Product not found"}%